# File: .github/workflows/refreshLeaderboards.yml
name: refresh-leaderboards
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/setup-node

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 #install the python needed

      - name: Refresh and commit new leaderboard 📡
        run: |
          node ./scripts/process_campaign.js
          python ./scripts/main_lb.py
          ls -ahl ./public
          git config --global user.name "Refresh lb action"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update leaderboard" || echo "No changes to commit"
          git push || echo "No changes to commit"
